import type { ExtractionResult } from './extraction';
import type { DeckPlan, SlideScreenshotIndex } from './slides';
import type { StandardsSelection } from './standards';

// Teacher lesson inputs - what teacher enters or confirms
export interface LessonInputs {
  // Basic info
  lessonTitle?: string;
  gradeLevel: 'K'; // Kindergarten only for now
  subject: 'ELA';
  
  // Phonics
  phonicsFocus?: {
    skillTag: string;
    humanLabel: string;
    examples?: string[];
  };
  
  // Sight words
  sightWords?: string[];
  
  // Vocabulary
  vocabulary?: {
    word: string;
    kidDefinition?: string;
    imageHint?: string;
  }[];
  
  // Story
  story?: {
    title?: string;
    pages?: {
      pageNumber?: number;
      imageUrl?: string;
      text?: string;
    }[];
  };
  
  // Discussion
  discussionQuestions?: string[];
  
  // Songs/Videos
  songs?: {
    title: string;
    youtubeUrl?: string;
  }[];
  
  // Skill focus
  skillFocusTags?: string[];
  
  // Notes
  teacherNotes?: string;
  
  // Deck settings
  deckIntensity?: 'Light' | 'Standard' | 'Full';
  themeId?: string;
}

// File reference
export interface LessonFileRef {
  fileId: string;
  fileName: string;
  fileType: 'pptx' | 'pdf' | 'image';
  fileSize: number;
  uploadedAt: string;
  category: 'reference' | 'lesson'; // reference = context, lesson = extract
  storageUrl?: string;
  hash?: string;
}

export interface LessonFileIndex {
  lessonId: string;
  files: LessonFileRef[];
}

// Complete lesson record
export interface LessonRecord {
  id: string;
  createdAt: string;
  updatedAt: string;
  
  // Teacher inputs (always takes precedence)
  inputs: LessonInputs;
  
  // File references
  files: LessonFileRef[];
  
  // Extraction results (if files were processed)
  extraction?: ExtractionResult;
  
  // Standards selection (teacher-confirmed)
  standards?: StandardsSelection;
  
  // Generated deck plan
  deckPlan?: DeckPlan;
  
  // Screenshots
  screenshots?: SlideScreenshotIndex;
  
  // Status tracking
  status: 'draft' | 'extracting' | 'review' | 'generating' | 'ready' | 'error';
  
  // Metadata
  metadata?: {
    ocrEnabled?: boolean;
    autoGenerated?: boolean;
    warnings?: string[];
  };
}

// Lesson creation request
export interface CreateLessonRequest {
  inputs: LessonInputs;
  files?: File[];
  options?: {
    enableOcr?: boolean;
    skipExtraction?: boolean;
  };
}

// Lesson update request
export interface UpdateLessonRequest {
  lessonId: string;
  inputs?: Partial<LessonInputs>;
  standards?: StandardsSelection;
  deckPlan?: DeckPlan;
}
